# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Custos < Formula
  desc "The missing terraform plan for HashiCorp Vault policies"
  homepage "https://github.com/timkrebs/custos"
  version "0.1.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timkrebs/custos/releases/download/v0.1.0/custos_0.1.0_darwin_amd64.tar.gz"
      sha256 "e786b51cca4830dbc325dc392847cc7021fd0d40cd746331367260383e3d40ef"

      define_method(:install) do
        bin.install "custos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timkrebs/custos/releases/download/v0.1.0/custos_0.1.0_darwin_arm64.tar.gz"
      sha256 "9fb01c39c367cb198363843aa3ee7ba31232be9d1824ac3475f116844e7a51ac"

      define_method(:install) do
        bin.install "custos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timkrebs/custos/releases/download/v0.1.0/custos_0.1.0_linux_amd64.tar.gz"
      sha256 "5096289227d8e8a3d56a06c78f3e6ddc55b6d5d628042e14fa146d3b9d18d859"
      define_method(:install) do
        bin.install "custos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timkrebs/custos/releases/download/v0.1.0/custos_0.1.0_linux_arm64.tar.gz"
      sha256 "36049afbb972f26addaf06b2e85c81c73676329065a02b5ae2867ff409be2948"
      define_method(:install) do
        bin.install "custos"
      end
    end
  end

  test do
    system "#{bin}/custos", "version"
  end
end
